version: "3.8"

services:
  hasura_metadata_db:
    image: postgres:15
    restart: always
    volumes:
      - hasura_metadata_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hasura_metadata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"

  room_booking_db:
    image: postgres:15
    restart: always
    volumes:
      - room_booking_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: room_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"

  payment_db:
    image: postgres:15
    restart: always
    volumes:
      - payment_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  guest_db:
    image: postgres:15
    restart: always
    volumes:
      - guest_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: guest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  auth_db:
    image: postgres:15
    restart: always
    volumes:
      - auth_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5437:5432"

  hasura:
    image: hasura/graphql-engine:v2.42.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:password@hasura_metadata_db:5432/hasura_metadata
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "supersecureadminsecret"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"this_is_a_much_longer_super_secret_key_123!","claims_namespace_path":"$","claims_map":{"x-hasura-allowed-roles":{"path":"x-hasura-allowed-roles"},"x-hasura-default-role":{"path":"x-hasura-default-role"},"x-hasura-user-id":{"path":"sub"}}}'
      ROOM_BOOKING_DATABASE_URL: postgres://postgres:password@room_booking_db:5432/room_booking
      PAYMENT_DATABASE_URL: postgres://postgres:password@payment_db:5432/payment
      GUEST_DATABASE_URL: postgres://postgres:password@guest_db:5432/guest
      AUTH_DATABASE_URL: postgres://postgres:password@auth_db:5432/auth
    depends_on:
      - hasura_metadata_db
      - room_booking_db
      - payment_db
      - guest_db
      - auth_db

  jwt-generator:
    build:
      context: ./jwt-generator
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    environment:
      JWT_SECRET: "this_is_a_much_longer_super_secret_key_123!"
      JWT_ALGORITHM: "HS256"
      AUTH_DATABASE_URL: postgres://postgres:password@auth_db:5432/auth
    depends_on:
      - auth_db
      - hasura

  room-service:
    build:
      context: ./room-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4001:4001"
    environment:
      ROOM_BOOKING_DATABASE_URL: postgres://postgres:password@room_booking_db:5432/room_booking
      HASURA_URL: http://hasura:8080/v1/graphql
      JWT_SECRET: "this_is_a_much_longer_super_secret_key_123!"
    depends_on:
      - room_booking_db
      - hasura

  bookings_service:
    build:
      context: ./bookings_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4002:4002"
    environment:
      HASURA_URL: http://hasura:8080/v1/graphql
      JWT_SECRET: "this_is_a_much_longer_super_secret_key_123!"
    depends_on:
      - hasura

  payment_service:
    build:
      context: ./payments_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4003:4003"
    environment:
      PAYMENT_DATABASE_URL: postgres://postgres:password@payment_db:5432/payment
      HASURA_URL: http://hasura:8080/v1/graphql
      JWT_SECRET: "this_is_a_much_longer_super_secret_key_123!"
    depends_on:
      - payment_db
      - hasura

  guest_service:
    build:
      context: ./guest_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4004:4004"
    environment:
      GUEST_DATABASE_URL: postgres://postgres:password@guest_db:5432/guest
      HASURA_URL: http://hasura:8080/v1/graphql
      JWT_SECRET: "this_is_a_much_longer_super_secret_key_123!"
    depends_on:
      - guest_db
      - hasura

volumes:
  hasura_metadata_data:
  room_booking_data:
  payment_data:
  guest_data:
  auth_data:
