services:
  hasura_metadata_db:
    image: postgres:15
    restart: always
    volumes:
      - hasura_metadata_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hasura_metadata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"

  room_booking_db:
    image: postgres:15
    restart: always
    volumes:
      - room_booking_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: room_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  payment_db:
    image: postgres:15
    restart: always
    volumes:
      - payment_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  guest_db:
    image: postgres:15
    restart: always
    volumes:
      - guest_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: guest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  hasura:
    image: hasura/graphql-engine:v2.42.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:password@hasura_metadata_db:5432/hasura_metadata
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      
      # Database URLs as environment variables
      ROOM_BOOKING_DATABASE_URL: postgres://postgres:password@room_booking_db:5432/room_booking
      PAYMENT_DATABASE_URL: postgres://postgres:password@payment_db:5432/payment
      GUEST_DATABASE_URL: postgres://postgres:password@guest_db:5432/guest
    depends_on:
      - hasura_metadata_db
      - room_booking_db
      - payment_db
      - guest_db

volumes:
  hasura_metadata_data:
  room_booking_data:
  payment_data:
  guest_data:
